/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.Writer;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author mzenm
 */
public class Barang extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        //memanggil method
        showTime();
        showDate();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utamaPanel = new javax.swing.JPanel();
        navigasiPanel = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        jumlahBarangPanel = new javax.swing.JPanel();
        lblJumlah = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaReport = new javax.swing.JTextArea();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        hargaTertinggiPanel = new javax.swing.JPanel();
        lblTertinggi = new javax.swing.JLabel();
        totalHargaPanel = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        hargaTerendahPanel = new javax.swing.JPanel();
        lblTerendah = new javax.swing.JLabel();
        inputanPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblKeluar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Inventaris Barang");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N

        utamaPanel.setBackground(new java.awt.Color(153, 102, 255));

        navigasiPanel.setBackground(new java.awt.Color(204, 204, 255));

        btnTambah.setBackground(new java.awt.Color(102, 153, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 153, 51));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Ubah.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 102));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 255, 204));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navigasiPanelLayout = new javax.swing.GroupLayout(navigasiPanel);
        navigasiPanel.setLayout(navigasiPanelLayout);
        navigasiPanelLayout.setHorizontalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasiPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        navigasiPanelLayout.setVerticalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigasiPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah)
                    .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUbah)
                        .addComponent(btnHapus))
                    .addComponent(btnClear))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        outputPanel.setBackground(new java.awt.Color(204, 204, 255));
        outputPanel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jumlahBarangPanel.setBackground(new java.awt.Color(255, 255, 204));
        jumlahBarangPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        javax.swing.GroupLayout jumlahBarangPanelLayout = new javax.swing.GroupLayout(jumlahBarangPanel);
        jumlahBarangPanel.setLayout(jumlahBarangPanelLayout);
        jumlahBarangPanelLayout.setHorizontalGroup(
            jumlahBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jumlahBarangPanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jumlahBarangPanelLayout.setVerticalGroup(
            jumlahBarangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahBarangPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        TextAreaReport.setColumns(20);
        TextAreaReport.setRows(5);
        jScrollPane2.setViewportView(TextAreaReport);

        btnExport.setBackground(new java.awt.Color(255, 102, 153));
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Export.png"))); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnImport.setBackground(new java.awt.Color(255, 102, 153));
        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Import.png"))); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(255, 102, 153));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Laporan.png"))); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
        });

        hargaTertinggiPanel.setBackground(new java.awt.Color(204, 153, 255));
        hargaTertinggiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga Tertinggi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        javax.swing.GroupLayout hargaTertinggiPanelLayout = new javax.swing.GroupLayout(hargaTertinggiPanel);
        hargaTertinggiPanel.setLayout(hargaTertinggiPanelLayout);
        hargaTertinggiPanelLayout.setHorizontalGroup(
            hargaTertinggiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hargaTertinggiPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblTertinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        hargaTertinggiPanelLayout.setVerticalGroup(
            hargaTertinggiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaTertinggiPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTertinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        totalHargaPanel.setBackground(new java.awt.Color(255, 255, 204));
        totalHargaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Harga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        javax.swing.GroupLayout totalHargaPanelLayout = new javax.swing.GroupLayout(totalHargaPanel);
        totalHargaPanel.setLayout(totalHargaPanelLayout);
        totalHargaPanelLayout.setHorizontalGroup(
            totalHargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalHargaPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        totalHargaPanelLayout.setVerticalGroup(
            totalHargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalHargaPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hargaTerendahPanel.setBackground(new java.awt.Color(204, 153, 255));
        hargaTerendahPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga Terendah", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        javax.swing.GroupLayout hargaTerendahPanelLayout = new javax.swing.GroupLayout(hargaTerendahPanel);
        hargaTerendahPanel.setLayout(hargaTerendahPanelLayout);
        hargaTerendahPanelLayout.setHorizontalGroup(
            hargaTerendahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hargaTerendahPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTerendah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        hargaTerendahPanelLayout.setVerticalGroup(
            hargaTerendahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaTerendahPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTerendah, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalHargaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBarangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hargaTertinggiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargaTerendahPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLaporan))
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jumlahBarangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaTertinggiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(outputPanelLayout.createSequentialGroup()
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(outputPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(outputPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hargaTerendahPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalHargaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(30, 30, 30))
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        inputanPanel.setBackground(new java.awt.Color(204, 204, 255));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Barang", "Stok", "Jenis", "Harga"
            }
        ));
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblBarang.setGridColor(new java.awt.Color(153, 153, 153));
        tblBarang.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblBarang.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblBarang.setShowHorizontalLines(true);
        tblBarang.setShowVerticalLines(true);
        tblBarang.getTableHeader().setReorderingAllowed(false);
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);
        if (tblBarang.getColumnModel().getColumnCount() > 0) {
            tblBarang.getColumnModel().getColumn(0).setMinWidth(38);
            tblBarang.getColumnModel().getColumn(0).setMaxWidth(38);
            tblBarang.getColumnModel().getColumn(1).setMinWidth(170);
            tblBarang.getColumnModel().getColumn(1).setMaxWidth(170);
            tblBarang.getColumnModel().getColumn(2).setMinWidth(45);
            tblBarang.getColumnModel().getColumn(2).setMaxWidth(45);
            tblBarang.getColumnModel().getColumn(3).setMinWidth(115);
            tblBarang.getColumnModel().getColumn(3).setMaxWidth(115);
            tblBarang.getColumnModel().getColumn(4).setMinWidth(140);
            tblBarang.getColumnModel().getColumn(4).setMaxWidth(140);
        }

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("ID ");

        jLabel2.setText("Nama");

        jLabel3.setText("Stok");

        jLabel4.setText("Jenis");

        tfStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfStokKeyTyped(evt);
            }
        });

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Televisi", "Kulkas", "AC", "Kipas Angin", "Mesin Cuci", "Setrika" }));

        jLabel5.setText("Harga");

        tfHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfHargaKeyTyped(evt);
            }
        });

        jLabel6.setText(":");

        jLabel9.setText(":");

        jLabel10.setText(":");

        jLabel11.setText(":");

        jLabel12.setText(":");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfId)
                            .addComponent(tfNama)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(tfStok))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbJenis, 0, 151, Short.MAX_VALUE)
                            .addComponent(tfHarga))))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inputanPanelLayout = new javax.swing.GroupLayout(inputanPanel);
        inputanPanel.setLayout(inputanPanelLayout);
        inputanPanelLayout.setHorizontalGroup(
            inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        inputanPanelLayout.setVerticalGroup(
            inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        headerPanel.setBackground(new java.awt.Color(204, 204, 255));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/tanggal.png"))); // NOI18N
        headerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 45));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setText("Date");
        headerPanel.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 0, 96, 59));

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTime.setText("Time");
        headerPanel.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 122, 59));

        lblKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/Keluar.jpg"))); // NOI18N
        lblKeluar.setText("jLabel8");
        lblKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKeluarMouseClicked(evt);
            }
        });
        headerPanel.add(lblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 0, 45, 59));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setText("INVENTARIS BARANG");
        headerPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 0, -1, 59));

        javax.swing.GroupLayout utamaPanelLayout = new javax.swing.GroupLayout(utamaPanel);
        utamaPanel.setLayout(utamaPanelLayout);
        utamaPanelLayout.setHorizontalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        utamaPanelLayout.setVerticalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
     //Membuat variabel dan Tipedata
     String id = tfId.getText();
     String nama = tfNama.getText();
     String stok = tfStok.getText();
     String jenis = cmbJenis.getSelectedItem().toString();
     long harga = 0;
     String hargatext = tfHarga.getText();
     
     //Mengecek nilai yang di input
     if (tfId.getText().equals("") || tfNama.getText().equals("") || tfStok.getText().equals("") || tfHarga.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
                    "Error",JOptionPane.WARNING_MESSAGE);
     }else{
    // Pemeriksaan ID tidak boleh sama
    boolean idSudahAda = false;
    DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
    
    for (int i = 0; i < model.getRowCount(); i++) {
        if (id.equals(model.getValueAt(i, 0))) {
            idSudahAda = true;
            break;
        }
    }

    if (idSudahAda) {
        JOptionPane.showMessageDialog(null, "ID sudah terdaftar, masukkan ID yang berbeda",
                "Error", JOptionPane.WARNING_MESSAGE);
         
     }else{            
     //Menambahkan data ke dalam row
         harga = Long.parseLong (tfHarga.getText());
         model.addRow(new Object[] {id, nama, stok, jenis, harga});
         JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
     
        
     //Menghitung jumlah barang 
        int jumlah = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 2);
            if (value != null) {
                jumlah += Integer.parseInt(value.toString());           
        }
    }
        lblJumlah.setText(Integer.toString(jumlah));
        
     //Menghitung total harga
        long total = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
            if (value != null) {
               total += Long.parseLong(value.toString());
    }
}
        lblTotal.setText(Long.toString(total));
        
    // Menghitung harga tertinggi
        long tertinggi = 0; 
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                 harga = Long.parseLong(value.toString());
             if (harga > tertinggi) {
                tertinggi = harga;
        }
    }
}
        lblTertinggi.setText(Long.toString(tertinggi));
        
    // Menghitung harga terendah
        long terendah = Long.MAX_VALUE;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                harga = Long.parseLong(value.toString());
             if (harga < terendah) {
                terendah = harga;
        }
    }
}
        lblTerendah.setText(Long.toString(terendah));
        
     //Membersihkan field setelah data berhasil terinput
        tfId.setText("");
        tfNama.setText("");
        tfStok.setText("");
        cmbJenis.setSelectedItem("Televisi");
        tfHarga.setText(null);
        tfId.requestFocus();
        }     
    }
    }//GEN-LAST:event_btnTambahActionPerformed
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    //Mengecek pemilihan data
    if (tfId.getText().equals("") || tfNama.getText().equals("") || tfStok.getText().equals("") || tfHarga.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu..!",
                    "Error",JOptionPane.WARNING_MESSAGE);
     }else{
    //Konfirmasi hapus data
    int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
           if (ubah == JOptionPane.YES_OPTION) {

    //Menghapus data dalam row
    int getSelectedRowForDeletion = tblBarang.getSelectedRow();
    if (getSelectedRowForDeletion >= 0) {
        DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
        model.removeRow(getSelectedRowForDeletion);
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus"); 
         }
       }
 
     //Menghitung jumlah barang setelah menghapus data
        int jumlah = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 2);
            if (value != null) {
                jumlah += Integer.parseInt(value.toString());           
        }
    }
        lblJumlah.setText(Integer.toString(jumlah));
        
     //Menghitung total harga setelah menghapus data
        long total = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
            if (value != null) {
               total += Long.parseLong(value.toString());
    }
}
        lblTotal.setText(Long.toString(total));
        
    // Menghitung harga tertinggi setelah menghapus data
    long harga = 0;    
    long tertinggi = 0; 
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                 harga = Long.parseLong(value.toString());
             if (harga > tertinggi) {
                tertinggi = harga;
        }
    }
}
        lblTertinggi.setText(Long.toString(tertinggi));
        
    // Menghitung harga terendah setelah menghapus data
        long terendah = Long.MAX_VALUE;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                harga = Long.parseLong(value.toString());
             if (harga < terendah) {
                terendah = harga;
        }
    }
}
        lblTerendah.setText(Long.toString(terendah));
           
        tfId.setText("");
        tfNama.setText("");
        tfStok.setText("");
        cmbJenis.setSelectedItem("Televisi");
        tfHarga.setText(null);
        tfId.requestFocus();
    }//GEN-LAST:event_btnHapusActionPerformed
}
    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        //Membersihkan field dan combobox
        tfId.setText("");
        tfNama.setText("");
        tfStok.setText("");
        cmbJenis.setSelectedItem("Televisi");
        tfHarga.setText(null);
        tfId.requestFocus();
        
        //Membersihkan laporan
        TextAreaReport.setText("");
        
    }//GEN-LAST:event_btnClearMouseClicked
   
    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        //Menampilkan Data dari Jtable ke TextFiled
        int selectedRow = tblBarang.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
        tfId.setText(model.getValueAt(selectedRow, 0).toString());
        tfNama.setText(model.getValueAt(selectedRow, 1).toString());
        tfStok.setText(model.getValueAt(selectedRow, 2).toString());
        String comboSub = model.getValueAt(selectedRow, 3).toString();

        for (int i = 0; i < cmbJenis.getItemCount(); i++) {
            if (cmbJenis.getItemAt(i).toString().equalsIgnoreCase(comboSub)) {
        cmbJenis.setSelectedIndex(i);
        break;
         }
    }
        tfHarga.setText(model.getValueAt(selectedRow, 4).toString());

    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        //Mengecek pemilihan data
        if (tfId.getText().equals("") || tfNama.getText().equals("") || tfStok.getText().equals("") || tfHarga.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Pilih Data terlebih dahulu..!",
                    "Error",JOptionPane.WARNING_MESSAGE);
        }else{
    
        
        //Konfirmasi ubah data  
        int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin mengubah data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (ubah == JOptionPane.YES_OPTION) {
        //Mengubah data dalam row            
        int i = tblBarang.getSelectedRow();
        if (i >= 0)
        {
            DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
            model.setValueAt(tfId.getText(), i, 0);
            model.setValueAt(tfNama.getText(), i, 1);
            model.setValueAt(tfStok.getText(), i, 2);
            model.setValueAt(cmbJenis.getSelectedItem().toString(), i,3);
            model.setValueAt(tfHarga.getText(), i, 4);
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
        }
      }
     //Menghitung jumlah barang setelah mengubah data
        int jumlah = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 2);
            if (value != null) {
                jumlah += Integer.parseInt(value.toString());           
        }
    }
        lblJumlah.setText(Integer.toString(jumlah));
        
     //Menghitung total harga setelah mengubah data
        long total = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
            if (value != null) {
               total += Long.parseLong(value.toString());
    }
}
        lblTotal.setText(Long.toString(total));
        
    // Menghitung harga tertinggi setelah mengubah data
    long harga = 0;    
    long tertinggi = 0; 
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                 harga = Long.parseLong(value.toString());
             if (harga > tertinggi) {
                tertinggi = harga;
        }
    }
}
        lblTertinggi.setText(Long.toString(tertinggi));
        
    // Menghitung harga terendah setelah mengubah data
        long terendah = Long.MAX_VALUE;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                harga = Long.parseLong(value.toString());
             if (harga < terendah) {
                terendah = harga;
        }
    }
}
        lblTerendah.setText(Long.toString(terendah));
        
        tfId.setText("");
        tfNama.setText("");
        tfStok.setText("");
        cmbJenis.setSelectedItem("Televisi");
        tfHarga.setText(null);
        tfId.requestFocus();
    }//GEN-LAST:event_btnUbahActionPerformed
}
    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // Mengecek data masih kosong dalam row
        DefaultTableModel model = (DefaultTableModel)tblBarang.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada data untuk diexport", "Data kosong", JOptionPane.INFORMATION_MESSAGE);
            return;
        }else{
        // Export File
        try{
            BufferedWriter out = new BufferedWriter (new FileWriter("DataBarang.ext"));
            
            for(int i = 0; i < tblBarang.getRowCount(); i++){ // rows
                for (int j = 0; j < tblBarang.getColumnCount(); j++){ // columns
                    out.write(tblBarang.getValueAt(i, j).toString()+"/ ");
                }
                out.newLine();
            }            
            JOptionPane.showMessageDialog(null, "Berhasil Diexport dalam File");
            
            out.close();
        }catch (Exception e){
            System.err.println("Error: "+e.getMessage());
        }
        
    }//GEN-LAST:event_btnExportActionPerformed
}
    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // Import File     
        String filePath = "DataBarang.ext";
        File file = new File(filePath);
        try{
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
        DefaultTableModel model = (DefaultTableModel)tblBarang.getModel();
        Object[] lines = br.lines().toArray();
        
        for(int i = 0; i < lines.length; i++ ){
            String[] row = lines[i].toString().split("/ ");
            model.addRow(row);
        }            
        JOptionPane.showMessageDialog(null, "Berhasil mengimport data");
        
      //Menghitung jumlah barang setelah mengimport
        int jumlah = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 2);
            if (value != null) {
                jumlah += Integer.parseInt(value.toString());           
        }
    }
        lblJumlah.setText(Integer.toString(jumlah));
        
     //Menghitung total harga setelah mengimport
        long total = 0;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
            if (value != null) {
               total += Long.parseLong(value.toString());
    }
}
        lblTotal.setText(Long.toString(total));
        
    // Menghitung harga tertinggi setelah mengimport
    long harga = 0;    
    long tertinggi = 0; 
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                 harga = Long.parseLong(value.toString());
             if (harga > tertinggi) {
                tertinggi = harga;
        }
    }
}
        lblTertinggi.setText(Long.toString(tertinggi));
        
    // Menghitung harga terendah setelah mengimport
        long terendah = Long.MAX_VALUE;
        for (int i = 0; i < tblBarang.getRowCount(); i++) {
            Object value = tblBarang.getValueAt(i, 4);
             if (value != null) {
                harga = Long.parseLong(value.toString());
             if (harga < terendah) {
                terendah = harga;
        }
    }
}
        lblTerendah.setText(Long.toString(terendah));
        
        }catch (Exception e){
            System.err.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        //Header Laporan
        TextAreaReport.setText(TextAreaReport.getText() + "=====================================\n");
        TextAreaReport.setText(TextAreaReport.getText() + "                      LAPORAN                \n");
        TextAreaReport.setFont(TextAreaReport.getFont().deriveFont(Font.BOLD, 14f));
        TextAreaReport.setText(TextAreaReport.getText() + "=====================================\n");
        // Laporan
        DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
        int nRow = model.getRowCount(), nCol = model.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
            for (int i = 0; i < nRow; i++) {
                for (int j = 0; j < nCol; j++) {
                tableData[i][j] = model.getValueAt(i, j);
            TextAreaReport.append(String.valueOf(tableData[i][j]) + "/ ");
            }
        TextAreaReport.append("\n");
      }
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void lblKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKeluarMouseClicked
       //Keluar Form
              int keluar = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (keluar == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
    }//GEN-LAST:event_lblKeluarMouseClicked

    private void tfHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHargaKeyTyped
        //memanggil method KeyTyped
        filterKeyTyped(evt);
        tfHarga.requestFocus();
    }//GEN-LAST:event_tfHargaKeyTyped

    private void tfStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStokKeyTyped
        //memanggil method KeyTyped
        filterKeyTyped(evt);
        tfStok.requestFocus();
    }//GEN-LAST:event_tfStokKeyTyped
 
    //Membuat method tanggal
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        String date = s.format(d);
        lblDate.setText(date);
    }

//Membuat method jam
    public void showTime(){
        new Timer (0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date d = new Date();
               SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
               String time = s.format(d);
               lblTime.setText(time);
            }
        }).start();
    }

    //Membuat method filter Nilai harus berupa angka
    private void filterKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Error..!!!Masukan Hanya Angka ");
            evt.consume();
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaReport;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JPanel hargaTerendahPanel;
    private javax.swing.JPanel hargaTertinggiPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel inputanPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jumlahBarangPanel;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKeluar;
    private javax.swing.JLabel lblTerendah;
    private javax.swing.JLabel lblTertinggi;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel navigasiPanel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfStok;
    private javax.swing.JPanel totalHargaPanel;
    private javax.swing.JPanel utamaPanel;
    // End of variables declaration//GEN-END:variables
}
